name: Start building
'on': push
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 The name of your branch is"
